services:
  # Backend Service
  - type: web
    name: clinical-trial-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python start_backend.py --host 0.0.0.0 --port $PORT --reload false"
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
      - key: CORS_ORIGINS
        value: "https://clinical-trial-frontend.onrender.com,http://localhost:5173,http://localhost:3000"
      - key: LOG_LEVEL
        value: "INFO"
      - key: PYTHONPATH
        value: "/opt/render/project/src/backend"

  # Frontend Service  
  - type: web
    name: clinical-trial-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: "cd frontend && npm ci && npm run build"
    startCommand: "cd frontend && npx serve -s dist -l $PORT"
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: clinical-trial-backend
          property: host
      - key: NODE_ENV
        value: "production" 